[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4d5d57"
red = "#ff7e3b"
green = "#7bdcb5"
yellow = "#fcd16b"
blue = "#8ad4e4"
magenta = "#b394b9"
cyan = "#9df2ea"
white = "#f0f9f7"
[colors.normal]
black = "#1f2e29"
red = "#d0502a"
green = "#4e8e78"
yellow = "#d1ae5b"
blue = "#396b78"
magenta = "#645a72"
cyan = "#54a6a1"
white = "#c9d7d3"

[colors.primary]
background = "#172624" # very deep ocean green
foreground = "#c0e9e6" # ethereal light for text

[colors.cursor]
cursor = "#ffb46a"      # flame cursor
text = "CellBackground"

[colors.selection]
background = "#2a3f3a"  # deep water shadow
text = "CellForeground"
[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"
#:%s/foo/spam/g
[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 15000

[window]
dynamic_padding = false
opacity = 10000
title = "tty0"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
